### PR TITLE
Fix trailing newline in code blocks

### LINKED ISSUE #47: Too many empty lines around ```code```
For the LTSP5 package, we switched our manpage sources from .xml to .md and we started using go-md2man. After Debian Buster was released and its man pages went online, we noticed a problem.

The man pages generated by `go-md2man` display fine when viewed under `man`. But when distributions use mandoc to publish them as .html pages online, a lot of empty lines are included in the html output, around the markdown ```code``` blocks (and I think elsewhere too).

As an example, see our lts.conf man page, as produced by go-md2man and then published by Debian's mandoc:
https://manpages.debian.org/unstable/ltsp-server/lts.conf.5.en.html

Search for the following line, and see how many empty lines are around it:
FSTAB_1="server:/home /home   nfs  defaults,nolock 0  0"

Our previous lts.conf manpage, that wasn't using go-md2man, displays a lot less empty lines:
https://manpages.debian.org/unstable/ltsp-docs/lts.conf.5.en.html

`Ronn` also manages to convert our new markdown-based man pages without extra empty lines, so I believe it's an issue with go-md2man. Thanks!

### PR DESCRIPTION
**Pull request by cpuguy83**
Given this input:

> ```
> some code
> ```

We were adding an additional newline character before the code close tag even though the code block by definition already includes that newline.

e.g., blackfriday is hadning us `some code\n` as the literal content of the code block.

fixes #47

### CODE REVIEW

File: md2man/roff_test.go [hunk 1]
```diff
@@ -13,10 +13,14 @@ type TestParams struct {
...
 	tests := []string{
 		"```\nsome code\n```\n",
-		".nh\n\n.EX\nsome code\n\n.EE\n",
+		".nh\n\n.EX\nsome code\n.EE\n",
 
 		"```bash\necho foo\n```\n",
-		".nh\n\n.EX\necho foo\n\n.EE\n",
+		".nh\n\n.EX\necho foo\n.EE\n",
+
+		// make sure we litteral new lines surrounding in the markdown block are preserved as they are intentional
```
Comment (kolyshkin) [inline md2man/roff_test.go:21]: `s/we litteral/the literal/`

**Comment by kolyshkin** [comment]
Overall LGTM, but let me try that on some more inputs first.

File: md2man/roff_test.go (hunk 1 above)
Comment (cpuguy83) [reply md2man/roff_test.go]: Fixed.

**Comment by bartekpacia** [comment]
Hi! Thank you very much for this module. I'd like to ask when this PR will be merged?

**Review by thaJeztah — APPROVED** [review]
LGTM

**Comment by cpuguy83** [comment]
v2.0.4 includes this fix.
